# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31894   # NodePort assigned in your Service
    hostPort: 31894        # Map to your Windows host
    protocol: TCP
